### PR TITLE
Update config.ini

### PR DESCRIPTION
**Pull request by mustcoded**
# ADD FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet.

## I checked the following required validations: (mark all 4 with [x])

1. [ x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=http://leftmouseclickin.com/category/python-ch/feed/ and it is valid!
2. [ x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [ x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [ x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

The above is the Chinese language version of the python feed.

### CODE REVIEW

**Comment by rochacbruno** [comment]
Hi,

Your feed already exists in the planet with the tag `python`

Looks like you are adding a new tag `python-ch` which is for Chinese content?

On planet we try to keep only content in English.

**Comment by mustcoded** [comment]
Sorry about that, Sir, because I have seen there are a few French language
rss feeds therefore I think it is ok for Chiese too. But ok, thank you
anyway, if possible can you provide me with any international websites that
accept the Chinese language python's content? I am a Chinese and I want to
share the Chinese content with the Chinese reader around the world, thank
you in advance!.

**Comment by holdenweb** [comment]
Perhaps you will have some luck contacting user groups in China? See
https://wiki.python.org/moin/LocalUserGroups#China for the information we
currently have.

Kind regards
Steve Holden

**Comment by mustcoded** [comment]
thank you for such valuable information, your kind Sir, I will take a look
at it  :)

**Comment by rochacbruno** [comment]
Hi @mustcoded thanks for understanding it.

We are trying to filter out those feeds in other languages and redirecting to local feeds when they exists, as this planet is international makes sense to try to keep only English content here.

:)

Bruno

**Comment by mustcoded** [comment]
谢谢你

**Pull request closed without merging**
