### PR TITLE
Add Bruno Oliveira's blog

### PR DESCRIPTION
**Pull request by nicoddemus**
This PR adds my blog to the list. Thanks!

### CODE REVIEW

**Comment by berkerpeksag** [comment]
Could you please update the feed URL to only list posts from http://nicoddemus.github.io/tag/python/ ? I think setting `TAG_FEED_ATOM` would be enough in your Pelican configuration. Thank you!

**Comment by nicoddemus** [comment]
Done! Thanks for the heads-up! :smile:

**Comment by berkerpeksag** [comment]
I'm not sure if it's a cache issue, but http://nicoddemus.github.io/tag/python goes to the HTML site. Perhaps you meant http://nicoddemus.github.io/tag/python/atom.xml :)

**Comment by nicoddemus** [comment]
Oops, wrong copy/paste. Sorry and thanks for the patience!

**Comment by berkerpeksag** [comment]
Thanks for the quick response! Merged in https://github.com/python/planet/commit/31268c1c23e8b3b269e74fa48f9e76949ec192f1. It should be online in an hour or two.

**Pull request closed without merging**
