### PR TITLE
Updated feed URL for Daniel Roy Greenfeld

### PR DESCRIPTION
**Pull request by pydanny**
# EDIT FEED
------------------------------------------------------------------------------
Hi, I want to change my current feed url from http://pydanny.github.com/feeds/python.atom.xml to https://www.pydanny.com/feeds/python.atom.xml

## I checked the following required validations:  (mark all 4 with [x])

1. [X] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=https://www.pydanny.com/feeds/python.atom.xml and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for changing my feed on Python Planet! :+1:

### CODE REVIEW

**Comment by Mariatta** [comment]
Hmm I just checked https://validator.w3.org/feed/check.cgi?url=https://www.pydanny.com/feeds/python.atom.xml it says `This feed does not validate` 😅

**Comment by pydanny** [comment]
Heh, just checked that and it catches things my homemade script does not. Let me see what I can do.

**Comment by pydanny** [comment]
Argh, my Pelican is so ancient the atom it renders is wacky. It's valid XML, which my script caught, but nothing else is good.

**Comment by pydanny** [comment]
The feed is passing validation now: http://pydanny.github.com/feeds/python.atom.xml to https://www.pydanny.com/feeds/python.atom.xml

**Comment by pydanny** [comment]
Thanks @Mariatta!

**Comment by pydanny** [comment]
@Mariatta, is there any other reason why my articles aren't appearing on http://planetpython.org?

**Comment by Mariatta** [comment]
Sorry about this, @pydanny :disappointed:  I asked @MarkMangoba for help and he's looking into it now :smiley:

**Comment by pydanny** [comment]
@Mariatta, @MarkMangoba Apologies for being such a pain in getting this working. Your efforts with Planet Python are appreciated!

**Comment by pydanny** [comment]
Because Pelican was blowing up with a code that was forcing me to dig into its source code (my blog is supposed to be easy to maintain), I reverted back to the previous version of Pelican, the one that renders the invalid feed. 

At some point I'll migrate off Pelican. In the meantime, you don't have to try to get my borked feed working in Planet.

**Comment by Mariatta** [comment]
So I think this is actually related to https://github.com/python/planet/issues/193
Will keep you posted of any updates.

**Pull request merged**
