### PR TITLE
Add GoDjango RSS feed

### PR DESCRIPTION
**Pull request by buddylindsey**
# ADD FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet.

## I checked the following required validations: (mark all 4 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

### CODE REVIEW

**Comment by tseaver** [comment]
Your feed should appear in the next update cycle.

**Comment by buddylindsey** [comment]
Thank you. I appreciate it.

**Comment by vasudevram** [comment]
@tseaver and others managing this: FYI, no new tweets about posts on Planet Python, have been appearing in the Twitter feed for @planetpython since this Nov 2. The last tweet was titled "Deploying Django Channels using Daphne" on Nov 2. IIRC I raised an issue about this a few days ago but do not remember seeing a reply (it might be that I missed it, sorry if so). Also is this the right place for reporting issues about that Planet Python Twitter account, or is this only for issues about the Planet itself? Thanks.

**Comment by tseaver** [comment]
@vasudevram The Planet team does not have control of the `@planetpython` Twitter account.

**Pull request merged**
