### PR TITLE
Update config.ini

### PR DESCRIPTION
**Pull request by mustcoded**
!!! Please choose one template below ADD FEED, EDIT FEED or INFORM a BUG/PROBLEM.
PLEASE: Remove this headline and the unused templates!!!

# ADD FEED / EDIT FEED
-------------------------------------------------------------------------------

Hi, I want to add my feed to the Python Planet. 

> IMPORTANT!!! **we need contact information to notify in case of any changes** Please send an email to `planet@python.org` title: `PR {number} sent to planet` with your email address + a link for the PR you opened.

## I checked the following required validations: (mark all 5 with [x])

1. [x ] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=https://kibiwebgeek.com/category/python/feed/ and it is valid!
2. [x ] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x ] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x ] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)
5. [x ] My feed contains only content in English language.

Thanks in advance for adding my feed to the PythonPlanet! :+1:

> NOTE: If you are adding a podcast feed please validate using http://castfeedvalidator.com/

### CODE REVIEW

**Comment by mustcoded** [comment]
I have done all the above, thank you!

**Comment by tseaver** [comment]
@mustcoded 

Thanks for sendind the e-mail to the list.  The PR still shows the `IslandT` entry at the top of the list, rather than sorted.  Do you need to push a commit from your local checkout?

**Comment by mustcoded** [comment]
Can you tell me where should it be? On top or at the bottom of the list? Or
can you adjust it for me, thank you very much!

**Comment by mustcoded** [comment]
update:

I have sorted the file according to the nickname with a new pull request

**Comment by tseaver** [comment]
Superseded by #364.

**Pull request closed without merging**
