### PR TITLE
Fix PyBites - feed now using https

### PR DESCRIPTION
**Pull request by pybites**
# EDIT FEED
------------------------------------------------------------------------------
Hi, I want to change my current feed url from http://pybit.es/feeds/all.rss.xml to https://pybit.es/feeds/all.rss.xml 
(we enabled SSL)

## I checked the following required validations:  (mark all 4 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for changing my feed on Python Planet! :+1:

### CODE REVIEW

**Comment by bbelderbos** [comment]
Thanks for the quick merge. I still don't see our PyBites articles (https://pybit.es) in the feed. How can I further debug this? I fixed https with this PR, I made sure that xml link works and is visible in our html. Thanks, Bob

**Comment by tseaver** [comment]
The feed update fails with:

```python
SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

**Comment by pybites** [comment]
Hm pulling it in with python feedparser works fine. Does this use curl? Or is it part of the repo's code I can check? Would be nice to have our articles show up again.

**Comment by pybites** [comment]
OK this is feedparser + python2 related. feedparser 4.1 does not work on Python3 so can only confirm that feedparser 5.1 + python3 works fine for our feed. The SSL error happens for more feeds, I am running a script and will open an issue.

**Comment by pybites** [comment]
upgrading to feedparser 5.1 on python2 won't work either: 

`(venv) [bbelderb@macbook tmp]$ python -V
Python 2.7.12
(venv) [bbelderb@macbook tmp]$ python -c "import feedparser; print(feedparser.__version__); print(feedparser.parse('https://pybit.es/feeds/all.rss.xml')['bozo'])"
5.2.1
1
(venv) [bbelderb@macbook tmp]$ python -c "import feedparser; print(feedparser.__version__); print(feedparser.parse('https://pybit.es/feeds/all.rss.xml')['bozo_exception'])"
5.2.1
<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)>`

**Comment by pybites** [comment]
@tseaver - I opened an issue: https://github.com/python/planet/issues/240 

I did make a script to loop over all the feeds and a lot gave ssl errors with feedparser 4.1. 

What's confusing though is that python bytes and dbader.org gave ssl errors too yet they do show up in planet python feed. 

Let me know if I can debug anything further. 

Thanks

**Pull request merged**
