### PR TITLE
Python 3 Upgrade (minimal)

### PR DESCRIPTION
**Pull request by offbyone**
Note: This PR is built on the work started by @JacobCoffee in https://github.com/python/planet/pull/569

A minimal Python 2 to 3 upgrade for planet. This is not a complete rewrite, it is the code changes necessary to allow the existing sequential feed updater to run using Python 3.12 rather than 2.... well, probably 2. Looking at this code I suspect it was Python 1, mostly.1

## Notable Changes

* replaced the templating system with jinja2
* replaced the HTML santization library with markupsafe
* unvendored feedparser
* unvendored _stdlib logging_.
* added a pyproject.toml
* added at least a small "this thing sort of works" test
* version 4.0

## Notable Unchanges

* the caching system is unchanged and still based on shelve
* no parallelization has been added
* only the least-invasive code changes necessary to generate the planet HTML were made

## Work left to do

* add more tests 
* add automation for the above tests
* refactor to make caching more inspectable and debuggable
* parallel feed downloading
* Confirm that https://github.com/python/cpython/issues/91228 is only affecting this on macOS

### CODE REVIEW

**Comment by ewdurbin** [comment]
Hi @offbyone! Thanks for picking up the torch here!

Is this in a state that generates usable output, or does it still have some ways to go before being (manually) testable?

**Comment by offbyone** [comment]
It generates useful input on first run, I'm still having some issues with caching. I expect to have time to dig into that this week.

**Comment by Mariatta** [comment]
Thank you @offbyone for the great work.
I'm not super well-versed with infra/devops kind of thing, but wondering if this is something we can like have deploy preview build kind of thing?

I'm also wishing we could automate the check for valid rss using GH actions  or as part of CI. Would that be possible to add? Should I open an issue about it?

**Comment by offbyone** [comment]
Opening the issue can't hurt; worst-case, it won't happen, but if it makes sense to do, we can.

**Comment by Mariatta** [comment]
Thanks. I've opened #579 and #580

**Comment by offbyone** [comment]
Okay, I'd call this ready to review. 

I don't know much about how it's currently running or deployed, although I can make some inferences based on the current code. I'm happy to sysadmin that shit if the owners of the host want me to.

**Comment by ewdurbin** [comment]
https://planetpython.org/3/ is now running and updating along side the main instance.

The initial result is a little confusing, I guess we'll see how it behaves over time?

**Comment by offbyone** [comment]
No, I think I see what's happening there.

There are two things that I'll want to address, one is full text feeds and the other is something that's possibly stateful. The DB has a field - `hidden` -- that it seems to infer from something about how "new" the feed is. Since I don't have the original DB, it's possible there are feeds not showing up in the new one that might otherwise be there. If you can get me the contents of `/srv/planetpython.org/` and `/srv/cache` from the old runner, I can see about getting things consistent.

**Comment by ewdurbin** [comment]
Archives of current state:

https://planetpython.org/cache-1728569965.tgz
https://planetpython.org/planetpython.org-1728569990.tgz

**Comment by offbyone** [comment]
Can you tell me which version of python (and, possibly, OS version and dbm library version) are involved in generating that? I hope it won't matter, but I might need to spin up a replica of the original to use those caches.

**Comment by JacobCoffee** [comment]
@offbyone 3.12.2

**Comment by ewdurbin** [comment]
```
ee@planet:~$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.6 LTS"
ee@planet:~$ uname -a
Linux planet 4.15.0-213-generic #224-Ubuntu SMP Mon Jun 19 13:30:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
ee@planet:~$ python
Python 2.7.17 (default, Mar  8 2023, 18:40:28) 
[GCC 7.5.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> 
```

**Comment by ewdurbin** [comment]
> @offbyone 3.12.2

That's the preview deploy, the state is from the original.

**Comment by ewdurbin** [comment]
Ah, @offbyone do you want the cache/output for the new version or the original?

**Comment by offbyone** [comment]
Honestly, "both is good" is even better. That way I can apples-to-apples it.

**Comment by ewdurbin** [comment]
for the new thing: https://planetpython.org/cache3-1728570557.tgz 

```
$ python3.12 
Python 3.12.2 (main, Oct 10 2024, 13:10:02) [GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
```

**Comment by offbyone** [comment]
Okay, so I have some good news and some bad news. 

The good news is that I can definitely get the ordering issues sorted.

The bad news is that as far as I can tell, I can't use the cache from the v2 version with v3, to retain the "hidden" state from the old feed cache. I'm looking into seeing how I can get that status, because it would radically change the feed if we lose it.

**Comment by offbyone** [comment]
I'm going to see if I can figure that one out somehow. I suspect I'm missing something with the weird ways dbm loads files.

**Pull request merged**
