### PR TITLE
Adding blog link

### PR DESCRIPTION
**Pull request by nerandell**
Discuss python language topics in general

### CODE REVIEW

**Comment by nerandell** [comment]
#78

**Comment by tseaver** [comment]
Can you please insert your entry so that the file remains sorted by URL?  It should fall between ` [https://maltheborch.com/rss?tags=python]` and `[https://nothingbutsnark.silvrback.com/feed]`.

**Comment by nerandell** [comment]
@tseaver Fixed the sorting issue.

**Comment by tseaver** [comment]
Thank you!  Your blog should appear in the next update cycle (an hour or two, usually).

**Pull request merged**
