### PR TITLE
added in-head css styling to make images responsive fix #24

### LINKED ISSUE #24: Responsive images on the planet
the current layout leaves very large images leak out of the visible area.
It is necessary, any change in the css to make the images are not outside the visible area

### PR DESCRIPTION
**Pull request by rochacbruno**
Fix #24 making images responsive on planet

### CODE REVIEW

**Comment by luzfcb** [comment]
@rochacbruno thanks for the quick reply, but the proposed solution is not keeping the aspect ratio


captura de tela de 2015-02-24 14 10 09

**Comment by luzfcb** [comment]
@rochacbruno update the pull-request and change `height: 100%;` to `height: auto;`

**Comment by luzfcb** [comment]
Another way:

```css
<style>
    /* Make images responsive */
    img {
	border: 0;
	height: auto;
	max-width: 100%;
	display: block;
	margin-left: auto;
	margin-right: auto;
	padding-top: 5px;
	padding-bottom: 35px;
    }
</style>

```

**Comment by rochacbruno** [comment]
@luzfcb I think it is not nice to force image centralization, should lead to problems when texts are placed around the images.

**Comment by rochacbruno** [comment]
I will wait some hours for comments, if no objection, I'll merge this today.

**Pull request merged**
