### PR TITLE
Update config.ini to reflect new Janusworx feed

### PR DESCRIPTION
**Pull request by jasonbraganza**
Hi, I want to add my feed to the Python Planet. or I want to change my current feed url from `https://janusworx.com/categories/planetpython.xml` to `https://janusworx.com/tags/planetpython/index.xml`

## I checked the following required validations: (mark all 5 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)
5. [x] My feed contains only content in English language.

Thanks in advance for adding my feed to the PythonPlanet! :+1:

### CODE REVIEW

**Comment by malemburg** [comment]
I had a look at the blog content you plan to submit to Planet Python, but this doesn't appear to be Python specific. Could you explain ? Thanks.

**Comment by jasonbraganza** [comment]
All the content, involved Python in some way of the other. If you look at the older entries, there is stuff about me learning Python specifically too.
This feed is definitely not going to be anything that does not touch my use of Python in one way or the other.
Thank you.

**Comment by malemburg** [comment]
Merged for now.

It would be great, if you could add more focus on Python to the posting you tag in your blog, more along the lines of https://janusworx.com/blog/updated-poemfeed/ and not just mentions of using Python.

**Comment by kushaldas** [comment]
I would like to vouch for @jasonbraganza's posts related to community & specially helping the new folks in relation to Python & related knowledge. His posts & he himself are a core part of the online training (https://foss.training) we provide to help people to become upstream contributors in Python and related ecosystem.

**Comment by jasonbraganza** [comment]
@malemburg That’s the plan.

**Comment by kushaldas** [comment]
Hehe, seems like by the time I posted the comment above @malemburg already merged it 26 seconds before :D

**Pull request merged**
