### PR TITLE
Fixed #86: Added https://alexmorozov.github.io to the blogroll.

### LINKED ISSUE #86: Add a https://alexmorozov.github.io blog
Will make a pull request for this.

### PR DESCRIPTION
**Pull request by alexmorozov**

### CODE REVIEW

**Comment by tseaver** [comment]
Can you please insert your section into the others in sorted order?  I.e., just above [https://clusterhq.com/feed.python.xml](https://github.com/python/planet/pull/87/files#diff-baa4c73fccd5f8bb6c09ebf574511c95L2210).

**Comment by alexmorozov** [comment]
Ah, I'm sorry. I've looked at the blog names first, not at their URLs, so it looked not sorted to me. Fixed.


>Среда, 11 ноября 2015, 5:49 -08:00 от Tres Seaver <notifications@github.com>:
>
>Can you please insert your section into the others in sorted order?  I.e., just above  https://clusterhq.com/feed.python.xml .
>—
>Reply to this email directly or  view it on GitHub .


---
С уважением,
Александр Морозов

**Comment by tseaver** [comment]
Thanks for fixing it.  Your feed should appear in the next update (an hour or two).

**Comment by alexmorozov** [comment]
Thanks a lot!

**Pull request merged**
