### PR TITLE
Add feed for Patrick Kennedy

### PR DESCRIPTION
**Pull request by patkennedy79**
Hi, I want to add my feed to the Python Planet.

## I checked the following required validations: (mark all 4 with [x])

1. [x] My feed is valid, I checked using https://validator.w3.org/feed/check.cgi?url=MY_FEED_URL and it is valid!
2. [x] My feed is a **Python Specific** feed, e.g: I am proposing the filtered tag or categorized feed url
3. [x] I only post content to this feed which is related to the Python language and its components and libraries. Or content that I consider interesting for the Python community.
4. [x] I am aware that once my feed is added it can take a few hours to start being fetched (according to the server update cycle)

Thanks in advance for adding my feed to the PythonPlanet! :+1:

### CODE REVIEW

**Comment by rochacbruno** [comment]
@patkennedy79 Your feed looks like too general http://www.patricksoftwareblog.com/feed/ I accessed and there is stuff about nginx and maybe you can post non python related stuff there.

Can you please update the pull request to a **tag** or **category** based feed filtering only specific Python stuff.

Thanks

**Comment by rochacbruno** [comment]
investigating your blog I found this http://www.patricksoftwareblog.com/tag/python/feed/

**Comment by patkennedy79** [comment]
Thank you for the suggestion to utilize a tag specific feed!  I was on the
fence about posts related to Nginx and Docker being applicable.  I'll
submit a new pull request this evening.

Thank you,
Patrick

**Comment by tseaver** [comment]
@patkennedy79 You could just update this PR, e.g.:

```bash
$ cd /path/to/planet
$ $EDITOR config/config.ini
$ git commit --amend config/config.ini
$ git push -f origin master
```

**Comment by patkennedy79** [comment]
Great recommendation to amend the last commit!  Just pushed the updated link with the ‘python’-specific feed.  Thanks again for all your help! -Patrick

**Comment by tseaver** [comment]
Your feed should appear in the next update cycle.

**Comment by patkennedy79** [comment]
Thanks so much!

**Pull request merged**
